### PR TITLE
add Fuzzy Matching

### PR DESCRIPTION
**Pull request by eternityspring**
add Fuzzy Matching

### CODE REVIEW

**Comment by gakimball** [comment]
What's the use-case for this?

**Comment by eternityspring** [comment]
the pageName can be a regular expression that means we can handle more than one file.
I have files:new-1.html,new-2.html...  then,i want display something in the files .
Without this patch it can be:`{{#ifpage 'new-1' 'new-2' ..}}`,but now:
`{{#ifpage 'new-*'}}`

**Comment by cmorrow** [comment]
Let's merge this in; unless I'm missing something. having a pagename RegEx or pageName FrontMater property is greatly needed; especially when matching nested root pages like "services/index.html". Matching on filename only is too basic.

**Comment by eternityspring** [comment]
maybe we can control this feature by a config file

**Pull request closed without merging**
